name: janus_client
description: A feature rich Janus Webrtc package
version: 2.4.2
homepage: https://github.com/shivanshtalwar0/flutter_janus_client

environment:
  sdk: ">=3.9.0 <4.0.0"
  flutter: ">=3.35.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: 9.0.0

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_webrtc: 1.2.1
  path_provider: 2.1.5
  http: 1.6.0
  web_socket_channel: 3.0.3
  uuid: 4.5.2
  logging: 1.3.0
  mqtt_client: 10.11.1
