name: janus_client
description: A feature rich Janus Webrtc package
version: 2.3.14
homepage: https://github.com/shivanshtalwar0/flutter_janus_client

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.29.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: 8.3.4

dependencies:
  flutter_web_plugins:
    sdk: flutter
  flutter:
    sdk: flutter
  flutter_webrtc: 1.0.0
  path_provider: 2.1.5
  http: 1.5.0
  web_socket_channel: 3.0.3
  uuid: 4.5.1
  logging: 1.3.0
  mqtt_client: 10.11.0
